# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Default task
    cmds:
      - task: run

  hello:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  run:
    desc: Run the Go application
    cmds:
      - go run main.go
  lint:
    desc: Run linter on the Go code
    cmds:
      - go vet ./...
      - golangci-lint run ./...
  audit:
    cmds:
      - govulncheck ./...
  fmt:
    desc: Format the Go code
    cmds:
      - go fmt ./...
      - goimports -w .
      - oxfmt
  update:
    desc: Update dependencies and format the Go code
    cmds:
      - go get -u ./...
      - go mod tidy

  build:
    desc: Build the Go application
    cmds:
      - go build -o go-hello -ldflags "-s -w" main.go
      - upx go-hello
